[general]
import = [
    "~/.config/alacritty/themes/gruvbox.toml"
]

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
size = 15

[window]
dimensions = { columns = 70, lines = 25 }
opacity = 0.8